### ISSUE TITLE
[Feature] - 3.2 이전 주가 정보를 서버로부터 받는다.

### ISSUE THREAD

**Issue by xjfcnfw3** [boostcampwm-2024/web17-juchumjuchum#10]
# Description
- 클라이언트가 쿼리스트링으로 서버에 데이터를 요청하면 서버는 주식 데이터를 전달한다.
 - 무한 스크롤 방식처럼 일정 길이의 데이터를 전달한다.
# To-do
- [ ] 쿼리스트링 설계
- [ ] 주식 API로부터 데이터를 받은 후 저장
    - [ ] 시간 정보 동기화 및 배치 프로그래밍
- [ ] 분, 시간, 일, 월, 년 등 다양한 단위의 데이터를 제공

# ETC
