### ISSUE TITLE
[Feature] - 3.3 주식 상세 페이지에서 다른 페이지로 넘어갈 수 있어야 한다

### ISSUE THREAD

**Issue by demian-m00n** [boostcampwm-2024/web17-juchumjuchum#11]
# Description

주식 상세 페이지에서 네비게이션 바를 통해서 메인 페이지, 마이 페이지 등 다른 페이지로 이동할 수 있어야 합니다.
- 홈 버튼을 클릭하면 메인 페이지로 이동합니다.
- 사용자 버튼을 클릭하면 마이 페이지로 이동합니다.
- 뒤로 가기를 클릭하면 이전 페이지로 이동합니다.

# To-do
FE
- [x] 네비게이션 컴포넌트 구현
- [x] 주식 상세 페이지 네비게이션 바 배치
- [x] 네비게이션 컴포넌트 별 라우팅 설정
- [x] 뒤로 가기 및 앞으로 가기 기능 검토

# ETC
