### ISSUE TITLE
[Feature] - 1.4 사용자는 특정 주식에서 주식 종류를 제외한 나머지(가격, 기한, 변동량)등을 변경할 수 있다.

### ISSUE THREAD

**Issue by swkim12345** [boostcampwm-2024/web17-juchumjuchum#13]
# Description
- 사용자는 마이페이지에서 주식 종류를 제외한 나머지를 변경할 수 있어야한다.
- 변경된 내역은 서버에 영속적으로 저장되어야 한다.

# To-do
- [ ] FE
    - [ ] 마이페이지에서 알림을 변경할 수 있는 페이지 혹은 모달
    - [ ] 가격, 기한, 변동량을 변경할 수 있는 UI 제공
    - [ ] 주식 종류는 조정할 수 없음.
    - [ ] 에러 메시지 처리
 
- [ ] BE
    - [ ] `POST` api /api/alarm 개발
    - [ ] 데이터 합의
    - [ ] swagger api 등록
    - [ ] 들어오는 값 validation
    - [ ] 유저, 알림 id가 일치해야지만 변경 가능

# ETC
