### ISSUE TITLE
[Feature] - 1.4 사용자는 특정 페이지에서 등록한 알림을 확인할 수 있다.

### ISSUE THREAD

**Issue by swkim12345** [boostcampwm-2024/web17-juchumjuchum#9]
# Description

- 마이페이지에서 클라이언트는 지금까지 등록한 알림내역을 확인할 수 있다.
- 알림은 자연어로 되어 있으며, 등록한 조건이 서술되어야 한다.

# To-do
- [ ] FE
    - [ ] 마이페이지 알람 내역
    - [ ] 알림 내역에서 가격, 기한, 변동량을 확인할 수 있어야 함

- [ ] BE
    - [ ] `GET` /api/alarm 개발
    - [ ] 데이터 합의
    - [ ] swagger 등록

# ETC
